package fi.haagahelia.HaagaTalk_proto;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import fi.haagahelia.HaagaTalk_proto.domain.Course;
import fi.haagahelia.HaagaTalk_proto.domain.CourseRepository;

@RunWith(SpringRunner.class)
@SpringBootTest
public class CourseRepositoryTest {

	@Autowired
	CourseRepository courseRepo;
	
	@Test
	public void newCourse_Save_Check() {
		Course course = new Course("courseCode-TEST", "test course", "teacher-id");
		courseRepo.save(course);
		
		// coursecode is a unique column and can be used to search
		Course fetchCourse = courseRepo.findByCourseCode("courseCode-TEST");
		// fetched object should exist and id should be autogenerated in the course object
		assertThat(fetchCourse.getId()).isNotNull();
	}
	
}
